package com.taufik.aseannatocompose.model

object FakeCountryDataSource {
    val dummyCountries = listOf(
        Country(
            countryId = 1,
            countryName = "Indonesia",
            countryInternationalName = "Republik Indonesia",
            countryFlagUrl = "https://upload.wikimedia.org/wikipedia/commons/thumb/9/9f/Flag_of_Indonesia.svg/125px-Flag_of_Indonesia.svg.png",
            countryDescription = "Negara kepulauan dengan total penduduk sekitar 272.229.372 jiwa (per Juni 2021) ini memiliki wilayah yang ada di antara benua Asia dan Australia. Posisi geografis yang berada sebagai titik silang perekonomian dunia ini pun sangat berpengaruh terhadap aktivitas perdagangan Indonesia. Menelisik sejarahnya, Indonesia sempat mengalami pahitnya kolonialisme Belanda dan juga Jepang selama lebih dari 300 tahun. Setelah Jepang kalah di Perang Dunia II, Republik Indonesia akhirnya berdiri menjadi negara yang merdeka sejak 17 Agustus 1945. Setelah 76 tahun Indonesia merdeka, negara dengan ibu kota Jakarta ini dipimpin oleh Presiden Joko Widodo. Ini bukanlah kali pertama Presiden Joko Widodo menjabat sebagai kepala negara. Setelah masa jabatannya habis di tahun 2019, Joko widodo kembali memenangkan pemilihan umum di tahun yang sama. Republik dengan bentuk negara kesatuan ini memiliki ideologi Pancasila yang sekaligus menjadi pedoman bagi seluruh warganya. Berasas demokrasi, Indonesia memiliki sistem pemerintahan presidensial.",
            countryHeadGovernment = "Joko Widodo (Presiden)",
            countryCapital = "Jakarta",
            countryIndependenceDay = "17 Agustus",
            countryLanguage = "Bahasa Indonesia",
            countryCurrency = "Rupiah (IDR)",
            countryLandArea = "1.904.569"
        ),
        Country(
            countryId = 2,
            countryName = "Thailand",
            countryInternationalName = "Kingdom of Thailand",
            countryFlagUrl = "https://asset.kompas.com/crops/Wd4Blwo5HQZ9941XQ3qz9xEwjlk=/0x0:250x167/750x500/data/photo/2020/02/19/5e4d1bd77a5a9.jpg",
            countryDescription = "Negara yang dijuluki sebagai Negeri Gajah ini adalah negara ASEAN yang tidak pernah merasakan kolonialisme bangsa Eropa. Berbatasan dengan Laos dan Kamboja, Thailand memiliki sistem pemerintahan berbentuk monarki konstitusional. Hal ini menjadikan kepala negara Thailand adalah seorang raja. Perihal urusan kenegaraan dan pemerintahan, Thailand menyerahkan pekerjaan kepada seorang Perdana Menteri. Saat ini (2021), Prayut Chan-o-cha menduduki posisi sebagai perdana menteri Thailand sejak tahun 2014 silam. Sebelum tahun 1980, para elite militer mendominasi politik di Thailand. Namun setelah dekade 1980-an, parlemen yang terpilih mulai memiliki pengaruh dalam politik di sana. Majelis Nasional yang terpilih juga mulai mengambil alih kekuasaan pemerintahan Thailand di tahun 1992. Meskipun kekuasaan militer sudah tidak lagi berpengaruh di pemerintahan, Thailand sempat dilanda kisruh akibat dua kali kudeta pada tahun 2006-2007 dan 2014.",
            countryHeadGovernment = "Prayut Chan-o-cha (Perdana Menteri)",
            countryCapital = "Bangkok",
            countryIndependenceDay = "5 Desember",
            countryLanguage = "Thai",
            countryCurrency = "Baht (THB)",
            countryLandArea = "513.120\","
        ),
        Country(
            countryId = 3,
            countryName = "Brunei Darussalam",
            countryInternationalName = "Brunei Darussalam",
            countryFlagUrl = "https://upload.wikimedia.org/wikipedia/commons/thumb/9/9c/Flag_of_Brunei.svg/2560px-Flag_of_Brunei.svg.png",
            countryDescription = "Negara mungil yang memiliki luas wilayah sekitar 5.765 km persegi ini memiliki standar hidup yang cukup tinggi, dan termasuk negara kaya di Asia. Sejak lama, Brunei mengandalkan minyak dan gas sebagai tulang punggung ekonomi. Terletak di bagian barat laut pulau Borneo (Kalimantan), Brunei adalah negara kesultanan Islam. Negara dengan ibu kota di Bandar Seri Begawan ini merdeka tahun 1984 setelah lama menjadi protektorat Inggris sejak 1888. Sistem pemerintahan Brunei berbentuk monarki absolut. Sultan sekaligus Perdana Menteri Brunei Darussalam saat ini adalah Hassanal Bolkiah. Budaya negara Brunei berakar kuat pada asal-usul melayunya yang juga tercermin dari gaya arsitektur, bahasa, dan adat. Maka itu, bahasa nasional Brunei adalah bahasa melayu, diikuti dengan bahasa Inggris sebagai bahasa kedua paling populer di negara tersebut. Brunei mulai resmi menjadi anggota ASEAN pada tahun 1984. Brunei bergabung menjadi anggota ASEAN setelah mendapatkan kemerdekaannya.",
            countryHeadGovernment = "Sultan Hassanal Bolkiah (Raja/Sultan/Perdana Menteri)",
            countryCapital = "Bandar Sri Begawan",
            countryIndependenceDay = "23 Februari",
            countryLanguage = "Melayu, Inggris, Mandarin",
            countryCurrency = "Dolar Brunei (BND)",
            countryLandArea = "5.765"
        ),
        Country(
            countryId = 4,
            countryName = "Vietnam",
            countryInternationalName = "Socialist Republic Of Vietnam",
            countryFlagUrl = "https://upload.wikimedia.org/wikipedia/commons/thumb/2/21/Flag_of_Vietnam.svg/250px-Flag_of_Vietnam.svg.png",
            countryDescription = "Negara Vietnam merupakan salah satu dari tiga negara terakhir yang resmi menjadi bagian dari ASEAN. Vietnam sebenarnya sudah menyatakan ketertarikannya untuk gabung dengan ASEAN sejak tahun 1992. Pada akhirnya, di tahun 1995, negara dengan ibu kota Hanoi itu mengikuti jejak kawan-kawannya di Asia Tenggara untuk bergabung dengan ASEAN. Bentuk negara Vietnam adalah sistem republik komunis, dengan Partai Komunis Vietnam tetap menjadi institusi politik yang dominan. Kepala negara Vietnam dijabat presiden, sementara urusan pemerintahan dipegang perdana menteri. Pham Minh Chinh baru saja terpilih jadi perdana menteri Vietnam pada April 2021, menggantikan Nguyễn Xuân Phúc. Perekonomian Vietnam yang berkembang pesat didukung oleh industri yang bergerak di bidang ritel, manufaktur, makanan, pertanian dan infrastruktur. Selain itu, sektor pariwisata juga menjadi salah satu kontributor terbesar bagi perekonomian Vietnam. Pada 2019, Vietnam dinobatkan sebagai Asia’s Leading Destination oleh WTA (World Travel Awards).",
            countryHeadGovernment = "Nguyễn Xuân Phúc (Perdana Menteri)",
            countryCapital = "Hanoi",
            countryIndependenceDay = "2 September",
            countryLanguage = "Vietnam",
            countryCurrency = "Dong (VND)",
            countryLandArea = "331.231"
        ),
        Country(
            countryId = 5,
            countryName = "Malaysia",
            countryInternationalName = "Malaysia",
            countryFlagUrl = "https://asset.kompas.com/crops/txVUgwjRJBYGDz5JUrwZs-Ep_8g=/0x0:250x125/780x390/data/photo/2020/02/19/5e4d1c91e29ec.jpg",
            countryDescription = "Sebagai salah satu dari lima negara pelopor ASEAN, negara tetangga Indonesia ini memiliki 13 negara bagian dan 3 wilayah federal. Setelah lepas dari jajahan Inggris, Malaysia sekarang menjadi bagian dari Commonwealth. Negara dengan ibu kota di Kuala Lumpur ini memiliki bahasa nasional yaitu Bahasa Malaysia, dengan mata uang Malaysian Ringgit. Saat ini, pemerintahan Malaysia menganut demokrasi parlementer dengan sistem monarki konstitusional. Oleh karena itu, raja berperan sebagai Kepala Negara sementara perdana menteri menduduki posisi sebagai kepala pemerintahan. Di akhir tahun 2020, populasi negara Malaysia mencapai 32,6 juta penduduk. Penduduk Malaysia datang dari berbagai kelompok etnis. Lebih dari 69% didominasi oleh bumiputera meliputi Orang Asli, Sarawak, Sabah dan penduduk asli Melayu.",
            countryHeadGovernment = "Ismail Sabri Yakob (Perdana Menteri)",
            countryCapital = "Kuala Lumpur",
            countryIndependenceDay = "31 Agustus",
            countryLanguage = "Melayu, Cina, Inggris, Tamil",
            countryCurrency = "Ringgit (MYR)",
            countryLandArea = "329.847"
        ),
        Country(
            countryId = 6,
            countryName = "Laos",
            countryInternationalName = "Lao People's Democratic Republic",
            countryFlagUrl = "https://asset.kompas.com/crops/1vwByzVDAIDujFeQ8VH38-nMKRM=/0x0:250x166/375x240/data/photo/2020/02/19/5e4d1d104c870.jpg",
            countryDescription = "Pada ulang tahun ASEAN yang ke-30, Laos memutuskan untuk bergabung dengan negara-negara Asia Tenggara lainnya di tahun 1997. Memiliki wilayah di jantung daratan Asia Tenggara, Laos adalah negara dengan populasi sekitar 7,169 juta penduduk. Menggantikan kerajaan Laos, Republik Demokratik Rakyat Laos didirikan pada Desember 1975. Dilansir dari laman UNDP, perkembangan Laos dalam pengentasan kemiskinan dapat dilihat secara signifikan selama dua dekade. Hal ini dibuktikan dengan data UNDP, bahwa tingkat kemiskinan turun 23% dari tahun 1992 hingga 2015. Laos memiliki sumber daya alam yang cukup melimpah. Sejumlah peninggalan bersejarah dan keindahan alam di Laos menjadikan negara ini populer bagi turis internasional.",
            countryHeadGovernment = "Thongloun Sisoulith (Perdana Menteri)",
            countryCapital = "Vientiane",
            countryIndependenceDay = "2 Desember",
            countryLanguage = "Lao, Prancis, Inggris",
            countryCurrency = "Kip (LAK)",
            countryLandArea = "237.955"
        ),
        Country(
            countryId = 7,
            countryName = "Singapura",
            countryInternationalName = "Republic of Singapore",
            countryFlagUrl = "https://upload.wikimedia.org/wikipedia/commons/thumb/4/48/Flag_of_Singapore.svg/1200px-Flag_of_Singapore.svg.png",
            countryDescription = "Selain Malaysia, Singapura juga menjadi salah satu negara ASEAN yang bergabung pada Commonwealth selepas merdeka dari Inggris. Singapura juga menjadi salah satu pelopor terbentuknya ASEAN. Negara pulau dengan populasi sekitar 5,7 juta penduduk ini memiliki ibu kota yang juga bernama Singapura. Ada empat bahasa resmi di Singapura, yakni Inggris, Mandarin, Melayu dan Tamil. Republik Parlementer merupakan bentuk pemerintahan Singapura, yang mana kepala negara dijabat oleh seorang presiden. Sementara itu, perdana menteri mempunyai peran sebagai kepala pemerintahan di Singapura. Lee Hsien Loong, anak tertua dari PM pertama Singapura yaitu Lee Kuan Yew, saat ini sedang menjabat sebagai perdana menteri. Loong sejak tahun 2014 hingga kini menyandang posisinya tersebut.",
            countryHeadGovernment = "Lee Hsien Loong (Perdana Menteri)",
            countryCapital = "Singapura",
            countryIndependenceDay = "9 Agustus",
            countryLanguage = "Inggris, Cina, Mandarin, Melayu, Tamil",
            countryCurrency = "Dolar Singapura (SGD)",
            countryLandArea = "721,5"
        ),
        Country(
            countryId = 8,
            countryName = "Myanmar",
            countryInternationalName = "Republic of the Union of Myanmar",
            countryFlagUrl = "https://upload.wikimedia.org/wikipedia/commons/thumb/8/8c/Flag_of_Myanmar.svg/2000px-Flag_of_Myanmar.svg.png",
            countryDescription = "Myanmar adalah negara terbesar di daratan Asia Tenggara. Myanmar memutuskan bergabung menjadi anggota resmi ASEAN pada Juli 1997. Sama dengan Laos, negara ini bergabung tepat pada ulang-tahun ASEAN ke-30. Wilayah Myanmar terletak di bagian barat daratan Asia Tenggara. Saat ini, populasi Myanmar mencapai 54,2 juta penduduk dengan ibu kota di Naypyitaw. Sebenarnya, bentuk pemerintahan Myanmar menganut sistem republik, dengan kepala negara seorang Presiden. Namun, Myanmar kini berada di bawah junta militer dan sampai pertengahan 2021 masih dilanda kemelut politik.",
            countryHeadGovernment = "Win Myint (Perdana Menteri)",
            countryCapital = "Nay Pyi Taw (Naypyidaw)",
            countryIndependenceDay = "4 Januari",
            countryLanguage = "Burma",
            countryCurrency = "Kyat (MMK)",
            countryLandArea = "676.578"
        ),
        Country(
            countryId = 9,
            countryName = "Filipina",
            countryInternationalName = "Republic of the Philippines",
            countryFlagUrl = "https://cdn.pixabay.com/photo/2012/04/10/22/58/philippines-26794_960_720.png",
            countryDescription = "Negara kepulauan yang terbentuk dari kurang lebih 7,000 pulau ini juga menjadi salah satu pelopor terbentuknya ASEAN. Terletak di sebelah barat lautan Pasifik, Filipina merupakan negara yang memiliki populasi mencapai lebih dari 109 juta penduduk pada tahun 2019. Selama kurang lebih 300 tahun, Filipina berada di bawah kolonialisme Spanyol. Pada tahun 1898, Filipina berhasil merdeka dari penjajahan Spanyol. Namun, AS merebut kekuasaan Spanyol di Filipina di perang Spanish-American War. Hal itu membuat Filipina dikuasai AS yang diikuti pecahnya perang Philippine-American War pada tahun 1899 hingga 1902. Invasi Spanyol dan Amerika memberikan banyak pengaruh terutama pada bahasa, agama dan gaya pemerintahan negara Filipina. Saat ini, Filipina menganut sistem demokrasi dan memiliki bentuk pemerintahan republik. Negara dengan ibu kota Manila itu menunjuk kepala negara yaitu Presiden melalui pemilu langsung.",
            countryHeadGovernment = "Rodrigo Duterte (Presiden)",
            countryCapital = "Manila",
            countryIndependenceDay = "12 Juni",
            countryLanguage = "Tagalog/Filipino, Inggris",
            countryCurrency = "Peso (PHP)",
            countryLandArea = "343.448"
        ),
        Country(
            countryId = 10,
            countryName = "Kamboja",
            countryInternationalName = "Kingdom of Cambodia",
            countryFlagUrl = "https://upload.wikimedia.org/wikipedia/commons/thumb/8/83/Flag_of_Cambodia.svg/2560px-Flag_of_Cambodia.svg.png",
            countryDescription = "Kamboja merupakan salah satu negara terakhir yang diterima menjadi bagian dari ASEAN di tahun 1999. Negara Kamboja terkenal sebagai pengekspor garmen. Sektor pariwisata Kamboja pun cukup kuat. Hal ini menjadikan Kamboja salah satu negara dengan pertumbuhan ekonomi pesat di Asia Tenggara. Ibu kota Kamboja yang terletak di Phnom Penh dulu dijuluki sebagai mutiara Asia. Julukan tersebut diberikan karena kota Phnom Penh menjadi pusat ekonomi, komersial, budaya dan wisata negara Kamboja. Kamboja menganut sistem monarki konstitusional dengan bentuk pemerintahan kerajaan. Sistem ini menjadikan raja sebagai kepala negara, sementara pemerintahan dipimpin oleh perdana menteri. Kini, Norodom Sihamoni adalah raja Kamboja sejak meneruskan tahta sang ayah pada 2004.",
            countryHeadGovernment = "Hun Sen (Perdana Menteri)",
            countryCapital = "Phnom Penh",
            countryIndependenceDay = "9 November",
            countryLanguage = "Khmer, Prancis, Inggris",
            countryCurrency = "Riel (KHR)",
            countryLandArea = "181.035"
        ),
        Country(
            countryId = 11,
            countryName = "Amerika Serikat",
            countryInternationalName = "United States of America",
            countryFlagUrl = "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e2/Flag_of_the_United_States_%28Pantone%29.svg/1200px-Flag_of_the_United_States_%28Pantone%29.svg.png",
            countryDescription = "Amerika Serikat terletak di tengah-tengah benua Amerika Utara, dibatasi oleh Kanada di sebelah utara dan Meksiko di sebelah selatan. Negara Amerika Serikat terbentang dari Samudra Atlantik di pesisir timur hingga Samudra Pasifik di pesisir barat, termasuk kepulauan Hawaii di lautan Pasifik, negara bagian Alaska di ujung utara benua Amerika, dan beberapa teritori lainnya. Negara Amerika, sebuah negara republik konstitusional federal, terdiri dari lima puluh negara bagian dan sebuah distrik federal.",
            countryHeadGovernment = "Joe Biden (Presiden)",
            countryCapital = "Washington, D.C.",
            countryIndependenceDay = "4 Juli",
            countryLanguage = "Inggris Amerika",
            countryCurrency = "Dolar Amerika (USD)",
            countryLandArea = "9.830.000"
        ),
        Country(
            countryId = 12,
            countryName = "Inggris",
            countryInternationalName = "England",
            countryFlagUrl = "https://upload.wikimedia.org/wikipedia/en/thumb/b/be/Flag_of_England.svg/1200px-Flag_of_England.svg.png",
            countryDescription = "Inggris (bahasa Inggris: England) adalah sebuah negara konstituen yang merupakan bagian dari Britania Raya.[6][7][8] Negara ini berbatasan dengan Skotlandia di sebelah utara dan Wales di sebelah barat, Laut Irlandia di barat laut, Laut Keltik di barat daya, serta Laut Utara di sebelah timur dan Selat Inggris, yang memisahkannya dari benua Eropa, di sebelah selatan. Sebagian besar wilayah Inggris terdiri dari bagian tengah dan selatan Pulau Britania Raya di Atlantik Utara. Inggris juga mencakup lebih dari 100 pulau kecil seperti Kepulauan Scilly dan Pulau Wight.",
            countryHeadGovernment = "Charles III (Raja)",
            countryCapital = "London",
            countryIndependenceDay = "2 Juli",
            countryLanguage = "Inggris",
            countryCurrency = "Poundsterling (GBP)",
            countryLandArea = "130.279"
        ),
        Country(
            countryId = 13,
            countryName = "Prancis",
            countryInternationalName = "France",
            countryFlagUrl = "https://upload.wikimedia.org/wikipedia/commons/thumb/1/18/Flag_of_France_%28lighter_variant%29.svg/250px-Flag_of_France_%28lighter_variant%29.svg.png",
            countryDescription = "Prancis adalah sebuah negara yang teritori metropolitannya terletak di Eropa Barat dan juga memiliki berbagai pulau dan teritori seberang laut yang terletak di benua lain.[7] Negara ini berbatasan dengan Belgia, Luksemburg, Jerman, Swiss, Italia, Monako, Andorra, dan Spanyol. Karena memiliki departemen seberang laut, Prancis juga berbagi perbatasan tanah dengan Brasil dan Suriname (berbatasan dengan Guyana Prancis), dan Sint Maarten (berbatasan dengan Saint-Martin). Prancis juga terhubung dengan Britania Raya oleh Terowongan Channel, yang berada di bawah Selat Inggris.",
            countryHeadGovernment = "Élisabeth Borne (Perdana Menteri)",
            countryCapital = "Paris",
            countryIndependenceDay = "14 Juli",
            countryLanguage = "Prancis",
            countryCurrency = "Euro (EUR)",
            countryLandArea = "643.801"
        ),
        Country(
            countryId = 14,
            countryName = "Belgia",
            countryInternationalName = "Kingdom of Belgium",
            countryFlagUrl = "https://upload.wikimedia.org/wikipedia/commons/thumb/9/92/Flag_of_Belgium_%28civil%29.svg/255px-Flag_of_Belgium_%28civil%29.svg.png",
            countryDescription = "Belgia sebuah negara di Eropa bagian barat. Di sebelah utara, Belgia berbatasan dengan Belanda, di sebelah timur dengan Jerman, di sebelah selatan dengan Prancis dan Luksemburg, dan di sebelah barat dengan Laut Utara, di seberang Britania Raya. Negara ini memiliki luas mencapai 30.689 kilometer persegi (11.849 sq mi) dan populasi lebih dari 11,5 juta, membuatnya negara ke-22 paling padat di dunia dan ke-6 paling padat di Eropa dengan kepadatan 376 per kilometer persegi (970/sq mi). Ibu kota dan kota terbesar di negara ini adalah Brussel; kota besar lain meliputi Antwerpen, Gent, Brugge, Namur dan Leuven.\n" +
                    "\n Negara ini adalah sebuah kerajaan konstitusional federal dengan sistem parlementer. Negara ini dibagi menjadi tiga negara bagian: Daerah Flandria di utara, Daerah Walonia di selatan, dan Daerah Ibukota Brussel.",
            countryHeadGovernment = "Alexander De Croo (Perdana Menteri)",
            countryCapital = "Brussels",
            countryIndependenceDay = "21 Juli",
            countryLanguage = "Belanda, Prancis, Jerman",
            countryCurrency = "Euro (EUR)",
            countryLandArea = "30.689 "
        ),
        Country(
            countryId = 15,
            countryName = "Belanda",
            countryInternationalName = "Nederland",
            countryFlagUrl = "https://upload.wikimedia.org/wikipedia/commons/thumb/2/20/Flag_of_the_Netherlands.svg/1280px-Flag_of_the_Netherlands.svg.png",
            countryDescription = "Belanda adalah sebuah negara yang sebagian besar terletak di Benua Eropa. Belanda merupakan bagian dari Kerajaan Belanda, sebuah negara monarki konstitusional yang mencakup seluruh bagian Belanda Eropa serta Belanda Karibia. Belanda terdiri dari dua belas provinsi di Eropa Barat dan tiga pulau teritori di Karibia. Belanda Eropa berbatasan dengan Laut Utara di utara dan barat, Belgia di selatan, dan Jerman di timur, serta berbagi perbatasan maritim dengan Belgia, Jerman, dan Britania Raya. Belanda menganut sistem pemerintahan demokrasi parlementer yang disusun sebagai negara kesatuan. Ibu kota dan kota terbesarnya adalah Amsterdam, sedangkan pusat pemerintahan dan kedudukan monarkinya berada di Den Haag. Belanda sebagai keseluruhan sering kali disebut Holland meskipun istilah tersebut hanya mencakup provinsi Holland Utara dan Holland Selatan.",
            countryHeadGovernment = "Mark Rutte (Perdana Menteri)",
            countryCapital = "Amsterdam",
            countryIndependenceDay = "5 Mei",
            countryLanguage = "Belanda",
            countryCurrency = "Euro (EUR)",
            countryLandArea = "41.54341.543"
        ),
        Country(
            countryId = 16,
            countryName = "Luksemburg",
            countryInternationalName = "Grand Duchy of Luxembourg",
            countryFlagUrl = "https://upload.wikimedia.org/wikipedia/commons/thumb/d/da/Flag_of_Luxembourg.svg/640px-Flag_of_Luxembourg.svg.png",
            countryDescription = "Luksemburg atau resminya Keharyapatihan Luksemburg atau Kadipaten Agung Luksemburg adalah sebuah negara yang tidak berbatasan dengan laut di Eropa bagian barat laut, berbatasan dengan Prancis (perbatasan panjang 73 km), Jerman (panjang perbatasan 138 km) dan Belgia (panjang perbatasan 148 km). Merupakan negara dengan luas 2.586 kilometer. Sejak 1815, Luksemburg merupakan satu satunya negara di dunia yang masih dipimpin oleh adipati atau haryapatih sebagai kepala negara.",
            countryHeadGovernment = "Xavier Bettel (Perdana Menteri)",
            countryCapital = "Luxembourg",
            countryIndependenceDay = "22 Juni",
            countryLanguage = "Luxembourgish, Jerman, Prancis",
            countryCurrency = "Euro (EUR)",
            countryLandArea = "2.586"
        ),
        Country(
            countryId = 17,
            countryName = "Kanada",
            countryInternationalName = "Dominion of Canada",
            countryFlagUrl = "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d9/Flag_of_Canada_%28Pantone%29.svg/125px-Flag_of_Canada_%28Pantone%29.svg.png",
            countryDescription = "Kanada, dengan nama asli Dominion of Canada, merupakan negara paling utara di kawasan Amerika Utara. Kerajaan ni terdiri dalam 10 provinsi dan 3 teritori, dengan menganut sistem desentralisasi. Kanada berdiri pada tahun 1867, setelah disahkannya undang-undang Konfederasi. Ottawa menjadi ibukota negara ini. Kantor Gubernur Jenderal, Perdana Menteri, serta parlemen nasional terletak di kota tersebut. Kanada pernah menjadi jajahan Prancis; yang kemudian direbut oleh Inggris, hingga hari kemerdekaannya. Kini, negara ini menjadi anggota La Francophonie, sekaligus negara Persemakmuran Inggris. Luas Kanada mencapai 9.970.610 km². Negara ini tergolong negara maju, yang perekonomiannya bergantung pada hasil alam.\n" +
                    "\n Kanada merupakaan monarki konstitusional, dengan pemerintahan yang berbentuk demokrasi parlementer federal. Raja Charles III menjadi kepala negara.",
            countryHeadGovernment = "Justin Trudeau (Perdana Menteri)",
            countryCapital = "Ottawa",
            countryIndependenceDay = "1 Juli",
            countryLanguage = "Inggris, Prancis",
            countryCurrency = "Dolar Kanada (CAD)",
            countryLandArea = "9.970.610"
        ),
        Country(
            countryId = 18,
            countryName = "Italia",
            countryInternationalName = "Repubblica Italiana",
            countryFlagUrl = "https://upload.wikimedia.org/wikipedia/en/thumb/0/03/Flag_of_Italy.svg/255px-Flag_of_Italy.svg.png",
            countryDescription = "Italia adalah sebuah negara kesatuan republik parlementer di Eropa. Terletak di jantung Laut Mediterania. Italia berbatasan dengan Prancis, Swiss, Austria, Slovenia, San Marino dan Vatikan. Italia mencakup area seluas 301.338 km² (116.347 mi²), dan dipengaruhi oleh iklim sedang dan iklim mediterania. Dilihat dari bentuknya, peta Italia berbentuk seperti sepatu bot atau di Italia sering disebut lo Stivale. Dengan jumlah penduduk mencapai 61 juta jiwa, Italia merupakan negara anggota Uni Eropa ketiga yang paling banyak penduduknya setelah Jerman dan Prancis.",
            countryHeadGovernment = "Giorgia Meloni (Perdana Menteri)",
            countryCapital = "Italia",
            countryIndependenceDay = "2 Juni",
            countryLanguage = "Italia",
            countryCurrency = "Euro (EUR)",
            countryLandArea = "301.338"
        ),
        Country(
            countryId = 19,
            countryName = "Portugal",
            countryInternationalName = "República Portuguesa",
            countryFlagUrl = "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5c/Flag_of_Portugal.svg/125px-Flag_of_Portugal.svg.png",
            countryDescription = "Portugal atau Portugis dengan nama resmi disebut sebagai Republik Portugis adalah sebuah negara kesatuan yang bersistem semi-presidensial dengan berbentuk republik konstitusional di Eropa Selatan. Negara ini berbatasan dengan Spanyol di sebelah utara dan sebelah timur, sedangkan di sebelah barat berbatasan dengan Samudra Atlantik. Selain itu, Portugal juga mempunyai daerah di Madeira, Azores dan Kepulauan Selvagens. Portugal mengklaim sebuah daerah kecil bernama \"Olivença\" yang dikuasai Spanyol sejak Kongres Wina. Nama lama atau latin dari negara ini adalah Lusitania.",
            countryHeadGovernment = "António Costa (Perdana Menteri)",
            countryCapital = "Lisbon",
            countryIndependenceDay = "1 Desember",
            countryLanguage = "Portugis, Lusitanian, Miranda",
            countryCurrency = "Euro (EUR)",
            countryLandArea = "92.212"
        ),
        Country(
            countryId = 20,
            countryName = "Islandia",
            countryInternationalName = "Ísland",
            countryFlagUrl = "https://upload.wikimedia.org/wikipedia/commons/thumb/c/ce/Flag_of_Iceland.svg/125px-Flag_of_Iceland.svg.png",
            countryDescription = "Islandia yang secara resmi bernama Republik Islandia, adalah sebuah negara Nordik yang terletak di sebelah barat laut Eropa dan sebelah utara Samudera Atlantik, yang terdiri dari Pulau Islandia dan beberapa pulau kecil disekitarnya. Islandia terletak 300 kilometer di sebelah timur Greenland dan 1.000 kilometer dari Norwegia." +
                    "\nNegara ini memiliki populasi sebanyak 332.529 penduduk dan luas 103.000 km persegi, menjadikannya negara dengan penduduk terjarang di Eropa. Ibu kota dan kota terbesar di negara ini adalah Reykjavík. Reykjavík dan sekitarnya adalah tempat tinggal bagi dua pertiga populasi.",
            countryHeadGovernment = "Katrín Jakobsdóttir",
            countryCapital = "Reykjavík",
            countryIndependenceDay = "17 Juni",
            countryLanguage = "Islandia",
            countryCurrency = "Króna Islandia (ISK)",
            countryLandArea = "102.775"
        ),
        Country(
            countryId = 21,
            countryName = "Denmark",
            countryInternationalName = "Kongeriget Danmark",
            countryFlagUrl = "https://upload.wikimedia.org/wikipedia/commons/thumb/9/9c/Flag_of_Denmark.svg/125px-Flag_of_Denmark.svg.png",
            countryDescription = "Denmark adalah negara Nordik yang paling kecil dan paling utara. Denmark terletak di sebelah barat daya dari Swedia dan selatan dari Norwegia. Negara ini terletak di Skandinavia, Eropa Utara sehingga termasuk Uni Eropa namun tidak berada di Semenanjung Skandinavia.\n" +
                    "\nDenmark berbatasan dengan Laut Baltik dan Laut Utara. Wilayahnya meliputi sebuah semenanjung di Jerman utara bernama Jylland (Jutlandia), Kepulauan Fyn (Funen), Sjælland (Zealand), Vendsyssel-Thy, Lolland, Falster, Bornholm dan ratusan pulau kecil, yang sering disebut kepulauan Denmark. Denmark pernah lama menguasai Laut Baltik. Sebelum penggalian Terusan Kiel, jalan air menuju Laut Baltik hanya dapat dilewati melalui tiga Selat Denmark. Satu-satunya batas darat Denmark adalah dengan Jerman, sedangkan tetangganya yang dibatasi oleh laut adalah Swedia di timur laut dan Norwegia di utara.",
            countryHeadGovernment = "Mette Frederiksen (Perdana Menteri)",
            countryCapital = "Kopenhagen",
            countryIndependenceDay = "5 Juni",
            countryLanguage = "Denmark",
            countryCurrency = "Euro (EUR)",
            countryLandArea = "42.933"
        ),
        Country(
            countryId = 22,
            countryName = "Norwegia",
            countryInternationalName = "Kongeriket Norge",
            countryFlagUrl = "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d9/Flag_of_Norway.svg/125px-Flag_of_Norway.svg.png",
            countryDescription = "Norwegia atau Kerajaan Norwegia adalah sebuah negara Nordik di Semenanjung Skandinavia, di bagian ujung barat yang berbatasan dengan Swedia, Finlandia, Rusia, Britania Raya di barat daya, dan 1.000 kilometer dari Islandia di arah barat. Pantainya yang berada di Samudra Atlantik Utara dan Laut Barents adalah lokasi dari fyord terkenal. Svalbard dan Jan Mayen berada di bawah kedaulatan Norwegia berdasarkan Traktat Svalbard. Norwegia memiliki sebuah pulau bernama Bouvet yang terletak di Samudra Atlantik bagian selatan. Luas total dari negara Norwegia adalah 385,207 km².",
            countryHeadGovernment = "Jonas Gahr Støre (Perdana Menteri)",
            countryCapital = "Oslo",
            countryIndependenceDay = "17 Mei",
            countryLanguage = "Norwegia",
            countryCurrency = "Krona Norwegia (NOK)",
            countryLandArea = "385.207"
        ),
        Country(
            countryId = 23,
            countryName = "Yunani",
            countryInternationalName = "Ellinikí Dimokratía",
            countryFlagUrl = "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5c/Flag_of_Greece.svg/125px-Flag_of_Greece.svg.png",
            countryDescription = "secara resmi bernama Republik Yunani, dikenal pada zaman purba sebagai Hellas, adalah sebuah negara tempat lahirnya budaya Dunia Barat yang berada di Eropa bagian tenggara, terletak di ujung selatan Semenanjung Balkan, di bagian timur Laut Tengah (Mediterania).",
            countryHeadGovernment = "Kyriakos Mitsotakis (Perdana Menteri)",
            countryCapital = "Athena",
            countryIndependenceDay = "25 Maret",
            countryLanguage = "Yunani",
            countryCurrency = "Euro (EUR)",
            countryLandArea = "131.957 "
        ),
        Country(
            countryId = 24,
            countryName = "Turkiye",
            countryInternationalName = "Türkiye Cumhuriyeti",
            countryFlagUrl = "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b4/Flag_of_Turkey.svg/125px-Flag_of_Turkey.svg.png",
            countryDescription = "Turkiye secara resmi disebut sebagai Republik Turkiye adalah sebuah negara kesatuan dengan sistem presidensial di kawasan Eurasia. Wilayahnya terbentang dari Semenanjung Anatolia di Asia Barat Laut hingga daerah Balkan di Eropa Tenggara. Turkiye berbatasan dengan Laut Hitam di sebelah utara; Bulgaria di sebelah barat laut; Yunani dan Laut Aegea di sebelah barat; Georgia di timur laut; Armenia, Azerbaijan, dan Iran di sebelah timur; Irak dan Suriah di tenggara; dan Laut Mediterania di sebelah selatan. Laut Marmara yang merupakan bagian dari Turkiye digunakan untuk menandai batas wilayah benua Eropa dan benua Asia, sehingga Turkiye dikenal sebagai negara transkontinental.",
            countryHeadGovernment = "Recep Tayyip Erdoğan (Presiden)",
            countryCapital = "Ankara",
            countryIndependenceDay = "29 Oktober",
            countryLanguage = "Turkiye",
            countryCurrency = "Lira Turki (TRY)",
            countryLandArea = "783,562"
        ),
        Country(
            countryId = 25,
            countryName = "Jerman",
            countryInternationalName = "Deutschland",
            countryFlagUrl = "https://upload.wikimedia.org/wikipedia/commons/thumb/b/ba/Flag_of_Germany.svg/125px-Flag_of_Germany.svg.png",
            countryDescription = "Jerman secara resmi disebut sebagai Republik Federal Jerman adalah negara berbentuk federasi di Eropa. Negara ini memiliki posisi ekonomi dan politik yang sangat penting di Eropa maupun di dunia. Dengan luas 357.021 kilometer persegi dan jumlah penduduk sekitar 82 juta jiwa, negara dengan 16 negara bagian (Bundesland, jamak: Bundesländer) ini menjadi anggota kunci organisasi Uni Eropa (penduduk terbanyak), penghubung transportasi barang dan jasa antarnegara sekawasan, serta menjadi negara dengan penduduk imigran ketiga terbesar di dunia.",
            countryHeadGovernment = "Olaf Scholz (Kanselir)",
            countryCapital = "Berlin",
            countryIndependenceDay = "3 Oktober",
            countryLanguage = "Jerman",
            countryCurrency = "Euro (EUR)",
            countryLandArea = "357.386"
        ),


    )
}