package com.taufik.aseannatocompose.model

object FakeCountryDataSource {
    val dummyCountries = listOf(
        Country(
            countryId = 1,
            countryName = "Indonesia",
            countryInternationalName = "Republik Indonesia",
            countryFlagUrl = "https://upload.wikimedia.org/wikipedia/commons/thumb/9/9f/Flag_of_Indonesia.svg/125px-Flag_of_Indonesia.svg.png",
            countryDescription = "Negara kepulauan dengan total penduduk sekitar 272.229.372 jiwa (per Juni 2021) ini memiliki wilayah yang ada di antara benua Asia dan Australia. Posisi geografis yang berada sebagai titik silang perekonomian dunia ini pun sangat berpengaruh terhadap aktivitas perdagangan Indonesia. Menelisik sejarahnya, Indonesia sempat mengalami pahitnya kolonialisme Belanda dan juga Jepang selama lebih dari 300 tahun. Setelah Jepang kalah di Perang Dunia II, Republik Indonesia akhirnya berdiri menjadi negara yang merdeka sejak 17 Agustus 1945. Setelah 76 tahun Indonesia merdeka, negara dengan ibu kota Jakarta ini dipimpin oleh Presiden Joko Widodo. Ini bukanlah kali pertama Presiden Joko Widodo menjabat sebagai kepala negara. Setelah masa jabatannya habis di tahun 2019, Joko widodo kembali memenangkan pemilihan umum di tahun yang sama. Republik dengan bentuk negara kesatuan ini memiliki ideologi Pancasila yang sekaligus menjadi pedoman bagi seluruh warganya. Berasas demokrasi, Indonesia memiliki sistem pemerintahan presidensial.",
            countryHeadGovernment = "Joko Widodo (Presiden)",
            countryCapital = "Jakarta",
            countryIndependenceDay = "17 Agustus",
            countryLanguage = "Bahasa Indonesia",
            countryCurrency = "Rupiah (IDR)",
            countryLandArea = "1.904.569"
        ),
        Country(
            countryId = 2,
            countryName = "Thailand",
            countryInternationalName = "Kingdom of Thailand",
            countryFlagUrl = "https://asset.kompas.com/crops/Wd4Blwo5HQZ9941XQ3qz9xEwjlk=/0x0:250x167/750x500/data/photo/2020/02/19/5e4d1bd77a5a9.jpg",
            countryDescription = "Negara yang dijuluki sebagai Negeri Gajah ini adalah negara ASEAN yang tidak pernah merasakan kolonialisme bangsa Eropa. Berbatasan dengan Laos dan Kamboja, Thailand memiliki sistem pemerintahan berbentuk monarki konstitusional. Hal ini menjadikan kepala negara Thailand adalah seorang raja. Perihal urusan kenegaraan dan pemerintahan, Thailand menyerahkan pekerjaan kepada seorang Perdana Menteri. Saat ini (2021), Prayut Chan-o-cha menduduki posisi sebagai perdana menteri Thailand sejak tahun 2014 silam. Sebelum tahun 1980, para elite militer mendominasi politik di Thailand. Namun setelah dekade 1980-an, parlemen yang terpilih mulai memiliki pengaruh dalam politik di sana. Majelis Nasional yang terpilih juga mulai mengambil alih kekuasaan pemerintahan Thailand di tahun 1992. Meskipun kekuasaan militer sudah tidak lagi berpengaruh di pemerintahan, Thailand sempat dilanda kisruh akibat dua kali kudeta pada tahun 2006-2007 dan 2014.",
            countryHeadGovernment = "Prayut Chan-o-cha (Perdana Menteri)",
            countryCapital = "Bangkok",
            countryIndependenceDay = "5 Desember",
            countryLanguage = "Thai",
            countryCurrency = "Baht (THB)",
            countryLandArea = "513.120\","
        ),
        Country(
            countryId = 3,
            countryName = "Brunei Darussalam",
            countryInternationalName = "Brunei Darussalam",
            countryFlagUrl = "https://upload.wikimedia.org/wikipedia/commons/thumb/9/9c/Flag_of_Brunei.svg/2560px-Flag_of_Brunei.svg.png",
            countryDescription = "Negara mungil yang memiliki luas wilayah sekitar 5.765 km persegi ini memiliki standar hidup yang cukup tinggi, dan termasuk negara kaya di Asia. Sejak lama, Brunei mengandalkan minyak dan gas sebagai tulang punggung ekonomi. Terletak di bagian barat laut pulau Borneo (Kalimantan), Brunei adalah negara kesultanan Islam. Negara dengan ibu kota di Bandar Seri Begawan ini merdeka tahun 1984 setelah lama menjadi protektorat Inggris sejak 1888. Sistem pemerintahan Brunei berbentuk monarki absolut. Sultan sekaligus Perdana Menteri Brunei Darussalam saat ini adalah Hassanal Bolkiah. Budaya negara Brunei berakar kuat pada asal-usul melayunya yang juga tercermin dari gaya arsitektur, bahasa, dan adat. Maka itu, bahasa nasional Brunei adalah bahasa melayu, diikuti dengan bahasa Inggris sebagai bahasa kedua paling populer di negara tersebut. Brunei mulai resmi menjadi anggota ASEAN pada tahun 1984. Brunei bergabung menjadi anggota ASEAN setelah mendapatkan kemerdekaannya.",
            countryHeadGovernment = "Sultan Hassanal Bolkiah (Raja/Sultan/Perdana Menteri)",
            countryCapital = "Bandar Sri Begawan",
            countryIndependenceDay = "23 Februari",
            countryLanguage = "Melayu, Inggris, Mandarin",
            countryCurrency = "Dolar Brunei (BND)",
            countryLandArea = "5.765"
        ),
        Country(
            countryId = 4,
            countryName = "Vietnam",
            countryInternationalName = "Socialist Republic Of Vietnam",
            countryFlagUrl = "https://upload.wikimedia.org/wikipedia/commons/thumb/2/21/Flag_of_Vietnam.svg/250px-Flag_of_Vietnam.svg.png",
            countryDescription = "Negara Vietnam merupakan salah satu dari tiga negara terakhir yang resmi menjadi bagian dari ASEAN. Vietnam sebenarnya sudah menyatakan ketertarikannya untuk gabung dengan ASEAN sejak tahun 1992. Pada akhirnya, di tahun 1995, negara dengan ibu kota Hanoi itu mengikuti jejak kawan-kawannya di Asia Tenggara untuk bergabung dengan ASEAN. Bentuk negara Vietnam adalah sistem republik komunis, dengan Partai Komunis Vietnam tetap menjadi institusi politik yang dominan. Kepala negara Vietnam dijabat presiden, sementara urusan pemerintahan dipegang perdana menteri. Pham Minh Chinh baru saja terpilih jadi perdana menteri Vietnam pada April 2021, menggantikan Nguyễn Xuân Phúc. Perekonomian Vietnam yang berkembang pesat didukung oleh industri yang bergerak di bidang ritel, manufaktur, makanan, pertanian dan infrastruktur. Selain itu, sektor pariwisata juga menjadi salah satu kontributor terbesar bagi perekonomian Vietnam. Pada 2019, Vietnam dinobatkan sebagai Asia’s Leading Destination oleh WTA (World Travel Awards).",
            countryHeadGovernment = "Nguyễn Xuân Phúc (Perdana Menteri)",
            countryCapital = "Hanoi",
            countryIndependenceDay = "2 September",
            countryLanguage = "Vietnam",
            countryCurrency = "Dong (VND)",
            countryLandArea = "331.231"
        ),
        Country(
            countryId = 5,
            countryName = "Malaysia",
            countryInternationalName = "Malaysia",
            countryFlagUrl = "https://asset.kompas.com/crops/txVUgwjRJBYGDz5JUrwZs-Ep_8g=/0x0:250x125/780x390/data/photo/2020/02/19/5e4d1c91e29ec.jpg",
            countryDescription = "Sebagai salah satu dari lima negara pelopor ASEAN, negara tetangga Indonesia ini memiliki 13 negara bagian dan 3 wilayah federal. Setelah lepas dari jajahan Inggris, Malaysia sekarang menjadi bagian dari Commonwealth. Negara dengan ibu kota di Kuala Lumpur ini memiliki bahasa nasional yaitu Bahasa Malaysia, dengan mata uang Malaysian Ringgit. Saat ini, pemerintahan Malaysia menganut demokrasi parlementer dengan sistem monarki konstitusional. Oleh karena itu, raja berperan sebagai Kepala Negara sementara perdana menteri menduduki posisi sebagai kepala pemerintahan. Di akhir tahun 2020, populasi negara Malaysia mencapai 32,6 juta penduduk. Penduduk Malaysia datang dari berbagai kelompok etnis. Lebih dari 69% didominasi oleh bumiputera meliputi Orang Asli, Sarawak, Sabah dan penduduk asli Melayu.",
            countryHeadGovernment = "Ismail Sabri Yakob (Perdana Menteri)",
            countryCapital = "Kuala Lumpur",
            countryIndependenceDay = "31 Agustus",
            countryLanguage = "Melayu, Cina, Inggris, Tamil",
            countryCurrency = "Ringgit (MYR)",
            countryLandArea = "329.847"
        ),
        Country(
            countryId = 6,
            countryName = "Laos",
            countryInternationalName = "Lao People's Democratic Republic",
            countryFlagUrl = "https://asset.kompas.com/crops/1vwByzVDAIDujFeQ8VH38-nMKRM=/0x0:250x166/375x240/data/photo/2020/02/19/5e4d1d104c870.jpg",
            countryDescription = "Pada ulang tahun ASEAN yang ke-30, Laos memutuskan untuk bergabung dengan negara-negara Asia Tenggara lainnya di tahun 1997. Memiliki wilayah di jantung daratan Asia Tenggara, Laos adalah negara dengan populasi sekitar 7,169 juta penduduk. Menggantikan kerajaan Laos, Republik Demokratik Rakyat Laos didirikan pada Desember 1975. Dilansir dari laman UNDP, perkembangan Laos dalam pengentasan kemiskinan dapat dilihat secara signifikan selama dua dekade. Hal ini dibuktikan dengan data UNDP, bahwa tingkat kemiskinan turun 23% dari tahun 1992 hingga 2015. Laos memiliki sumber daya alam yang cukup melimpah. Sejumlah peninggalan bersejarah dan keindahan alam di Laos menjadikan negara ini populer bagi turis internasional.",
            countryHeadGovernment = "Thongloun Sisoulith (Perdana Menteri)",
            countryCapital = "Vientiane",
            countryIndependenceDay = "2 Desember",
            countryLanguage = "Lao, Prancis, Inggris",
            countryCurrency = "Kip (LAK)",
            countryLandArea = "237.955"
        ),
        Country(
            countryId = 7,
            countryName = "Singapura",
            countryInternationalName = "Republic of Singapore",
            countryFlagUrl = "https://upload.wikimedia.org/wikipedia/commons/thumb/4/48/Flag_of_Singapore.svg/1200px-Flag_of_Singapore.svg.png",
            countryDescription = "Selain Malaysia, Singapura juga menjadi salah satu negara ASEAN yang bergabung pada Commonwealth selepas merdeka dari Inggris. Singapura juga menjadi salah satu pelopor terbentuknya ASEAN. Negara pulau dengan populasi sekitar 5,7 juta penduduk ini memiliki ibu kota yang juga bernama Singapura. Ada empat bahasa resmi di Singapura, yakni Inggris, Mandarin, Melayu dan Tamil. Republik Parlementer merupakan bentuk pemerintahan Singapura, yang mana kepala negara dijabat oleh seorang presiden. Sementara itu, perdana menteri mempunyai peran sebagai kepala pemerintahan di Singapura. Lee Hsien Loong, anak tertua dari PM pertama Singapura yaitu Lee Kuan Yew, saat ini sedang menjabat sebagai perdana menteri. Loong sejak tahun 2014 hingga kini menyandang posisinya tersebut.",
            countryHeadGovernment = "Lee Hsien Loong (Perdana Menteri)",
            countryCapital = "Singapura",
            countryIndependenceDay = "9 Agustus",
            countryLanguage = "Inggris, Cina, Mandarin, Melayu, Tamil",
            countryCurrency = "Dolar Singapura (SGD)",
            countryLandArea = "721,5"
        ),
        Country(
            countryId = 8,
            countryName = "Myanmar",
            countryInternationalName = "Republic of the Union of Myanmar",
            countryFlagUrl = "https://upload.wikimedia.org/wikipedia/commons/thumb/8/8c/Flag_of_Myanmar.svg/2000px-Flag_of_Myanmar.svg.png",
            countryDescription = "Myanmar adalah negara terbesar di daratan Asia Tenggara. Myanmar memutuskan bergabung menjadi anggota resmi ASEAN pada Juli 1997. Sama dengan Laos, negara ini bergabung tepat pada ulang-tahun ASEAN ke-30. Wilayah Myanmar terletak di bagian barat daratan Asia Tenggara. Saat ini, populasi Myanmar mencapai 54,2 juta penduduk dengan ibu kota di Naypyitaw. Sebenarnya, bentuk pemerintahan Myanmar menganut sistem republik, dengan kepala negara seorang Presiden. Namun, Myanmar kini berada di bawah junta militer dan sampai pertengahan 2021 masih dilanda kemelut politik.",
            countryHeadGovernment = "Win Myint (Perdana Menteri)",
            countryCapital = "Nay Pyi Taw (Naypyidaw)",
            countryIndependenceDay = "4 Januari",
            countryLanguage = "Burma",
            countryCurrency = "Kyat (MMK)",
            countryLandArea = "676.578"
        ),
        Country(
            countryId = 9,
            countryName = "Filipina",
            countryInternationalName = "Republic of the Philippines",
            countryFlagUrl = "https://cdn.pixabay.com/photo/2012/04/10/22/58/philippines-26794_960_720.png",
            countryDescription = "Negara kepulauan yang terbentuk dari kurang lebih 7,000 pulau ini juga menjadi salah satu pelopor terbentuknya ASEAN. Terletak di sebelah barat lautan Pasifik, Filipina merupakan negara yang memiliki populasi mencapai lebih dari 109 juta penduduk pada tahun 2019. Selama kurang lebih 300 tahun, Filipina berada di bawah kolonialisme Spanyol. Pada tahun 1898, Filipina berhasil merdeka dari penjajahan Spanyol. Namun, AS merebut kekuasaan Spanyol di Filipina di perang Spanish-American War. Hal itu membuat Filipina dikuasai AS yang diikuti pecahnya perang Philippine-American War pada tahun 1899 hingga 1902. Invasi Spanyol dan Amerika memberikan banyak pengaruh terutama pada bahasa, agama dan gaya pemerintahan negara Filipina. Saat ini, Filipina menganut sistem demokrasi dan memiliki bentuk pemerintahan republik. Negara dengan ibu kota Manila itu menunjuk kepala negara yaitu Presiden melalui pemilu langsung.",
            countryHeadGovernment = "Rodrigo Duterte (Presiden)",
            countryCapital = "Manila",
            countryIndependenceDay = "12 Juni",
            countryLanguage = "Tagalog/Filipino, Inggris",
            countryCurrency = "Peso (PHP)",
            countryLandArea = "343.448"
        ),
        Country(
            countryId = 10,
            countryName = "Kamboja",
            countryInternationalName = "Kingdom of Cambodia",
            countryFlagUrl = "https://upload.wikimedia.org/wikipedia/commons/thumb/8/83/Flag_of_Cambodia.svg/2560px-Flag_of_Cambodia.svg.png",
            countryDescription = "Kamboja merupakan salah satu negara terakhir yang diterima menjadi bagian dari ASEAN di tahun 1999. Negara Kamboja terkenal sebagai pengekspor garmen. Sektor pariwisata Kamboja pun cukup kuat. Hal ini menjadikan Kamboja salah satu negara dengan pertumbuhan ekonomi pesat di Asia Tenggara. Ibu kota Kamboja yang terletak di Phnom Penh dulu dijuluki sebagai mutiara Asia. Julukan tersebut diberikan karena kota Phnom Penh menjadi pusat ekonomi, komersial, budaya dan wisata negara Kamboja. Kamboja menganut sistem monarki konstitusional dengan bentuk pemerintahan kerajaan. Sistem ini menjadikan raja sebagai kepala negara, sementara pemerintahan dipimpin oleh perdana menteri. Kini, Norodom Sihamoni adalah raja Kamboja sejak meneruskan tahta sang ayah pada 2004.",
            countryHeadGovernment = "Hun Sen (Perdana Menteri)",
            countryCapital = "Phnom Penh",
            countryIndependenceDay = "9 November",
            countryLanguage = "Khmer, Prancis, Inggris",
            countryCurrency = "Riel (KHR)",
            countryLandArea = "181.035"
        ),
        Country(
            countryId = 11,
            countryName = "Amerika Serikat",
            countryInternationalName = "United States of America",
            countryFlagUrl = "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e2/Flag_of_the_United_States_%28Pantone%29.svg/1200px-Flag_of_the_United_States_%28Pantone%29.svg.png",
            countryDescription = "Amerika Serikat terletak di tengah-tengah benua Amerika Utara, dibatasi oleh Kanada di sebelah utara dan Meksiko di sebelah selatan. Negara Amerika Serikat terbentang dari Samudra Atlantik di pesisir timur hingga Samudra Pasifik di pesisir barat, termasuk kepulauan Hawaii di lautan Pasifik, negara bagian Alaska di ujung utara benua Amerika, dan beberapa teritori lainnya. Negara Amerika, sebuah negara republik konstitusional federal, terdiri dari lima puluh negara bagian dan sebuah distrik federal.",
            countryHeadGovernment = "Joe Biden (Presiden)",
            countryCapital = "Washington, D.C.",
            countryIndependenceDay = "4 Juli",
            countryLanguage = "Inggris Amerika",
            countryCurrency = "Dolar Amerika (USD)",
            countryLandArea = "9.830.000"
        ),
        Country(
            countryId = 12,
            countryName = "Inggris",
            countryInternationalName = "England",
            countryFlagUrl = "https://upload.wikimedia.org/wikipedia/en/thumb/b/be/Flag_of_England.svg/1200px-Flag_of_England.svg.png",
            countryDescription = "Inggris (bahasa Inggris: England) adalah sebuah negara konstituen yang merupakan bagian dari Britania Raya.[6][7][8] Negara ini berbatasan dengan Skotlandia di sebelah utara dan Wales di sebelah barat, Laut Irlandia di barat laut, Laut Keltik di barat daya, serta Laut Utara di sebelah timur dan Selat Inggris, yang memisahkannya dari benua Eropa, di sebelah selatan. Sebagian besar wilayah Inggris terdiri dari bagian tengah dan selatan Pulau Britania Raya di Atlantik Utara. Inggris juga mencakup lebih dari 100 pulau kecil seperti Kepulauan Scilly dan Pulau Wight.",
            countryHeadGovernment = "Charles III (Raja)",
            countryCapital = "London",
            countryIndependenceDay = "2 Juli",
            countryLanguage = "Inggris",
            countryCurrency = "Poundsterling (GBP)",
            countryLandArea = "130.279"
        ),
        Country(
            countryId = 13,
            countryName = "Prancis",
            countryInternationalName = "France",
            countryFlagUrl = "https://upload.wikimedia.org/wikipedia/commons/thumb/1/18/Flag_of_France_%28lighter_variant%29.svg/250px-Flag_of_France_%28lighter_variant%29.svg.png",
            countryDescription = "Prancis adalah sebuah negara yang teritori metropolitannya terletak di Eropa Barat dan juga memiliki berbagai pulau dan teritori seberang laut yang terletak di benua lain.[7] Negara ini berbatasan dengan Belgia, Luksemburg, Jerman, Swiss, Italia, Monako, Andorra, dan Spanyol. Karena memiliki departemen seberang laut, Prancis juga berbagi perbatasan tanah dengan Brasil dan Suriname (berbatasan dengan Guyana Prancis), dan Sint Maarten (berbatasan dengan Saint-Martin). Prancis juga terhubung dengan Britania Raya oleh Terowongan Channel, yang berada di bawah Selat Inggris.",
            countryHeadGovernment = "Élisabeth Borne (Perdana Menteri)",
            countryCapital = "Paris",
            countryIndependenceDay = "14 Juli",
            countryLanguage = "Prancis",
            countryCurrency = "Euro (EUR)",
            countryLandArea = "643.801"
        ),
        Country(
            countryId = 14,
            countryName = "Belgia",
            countryInternationalName = "Kingdom of Belgium",
            countryFlagUrl = "https://upload.wikimedia.org/wikipedia/commons/thumb/9/92/Flag_of_Belgium_%28civil%29.svg/255px-Flag_of_Belgium_%28civil%29.svg.png",
            countryDescription = "Belgia sebuah negara di Eropa bagian barat. Di sebelah utara, Belgia berbatasan dengan Belanda, di sebelah timur dengan Jerman, di sebelah selatan dengan Prancis dan Luksemburg, dan di sebelah barat dengan Laut Utara, di seberang Britania Raya. Negara ini memiliki luas mencapai 30.689 kilometer persegi (11.849 sq mi) dan populasi lebih dari 11,5 juta, membuatnya negara ke-22 paling padat di dunia dan ke-6 paling padat di Eropa dengan kepadatan 376 per kilometer persegi (970/sq mi). Ibu kota dan kota terbesar di negara ini adalah Brussel; kota besar lain meliputi Antwerpen, Gent, Brugge, Namur dan Leuven.\n" +
                    "\n Negara ini adalah sebuah kerajaan konstitusional federal dengan sistem parlementer. Negara ini dibagi menjadi tiga negara bagian: Daerah Flandria di utara, Daerah Walonia di selatan, dan Daerah Ibukota Brussel.",
            countryHeadGovernment = "Alexander De Croo (Perdana Menteri)",
            countryCapital = "Brussels",
            countryIndependenceDay = "21 Juli",
            countryLanguage = "Belanda, Prancis, Jerman",
            countryCurrency = "Euro (EUR)",
            countryLandArea = "30.689 "
        ),
        Country(
            countryId = 15,
            countryName = "Belanda",
            countryInternationalName = "Nederland",
            countryFlagUrl = "https://upload.wikimedia.org/wikipedia/commons/thumb/2/20/Flag_of_the_Netherlands.svg/1280px-Flag_of_the_Netherlands.svg.png",
            countryDescription = "Belanda adalah sebuah negara yang sebagian besar terletak di Benua Eropa. Belanda merupakan bagian dari Kerajaan Belanda, sebuah negara monarki konstitusional yang mencakup seluruh bagian Belanda Eropa serta Belanda Karibia. Belanda terdiri dari dua belas provinsi di Eropa Barat dan tiga pulau teritori di Karibia. Belanda Eropa berbatasan dengan Laut Utara di utara dan barat, Belgia di selatan, dan Jerman di timur, serta berbagi perbatasan maritim dengan Belgia, Jerman, dan Britania Raya. Belanda menganut sistem pemerintahan demokrasi parlementer yang disusun sebagai negara kesatuan. Ibu kota dan kota terbesarnya adalah Amsterdam, sedangkan pusat pemerintahan dan kedudukan monarkinya berada di Den Haag. Belanda sebagai keseluruhan sering kali disebut Holland meskipun istilah tersebut hanya mencakup provinsi Holland Utara dan Holland Selatan.",
            countryHeadGovernment = "Mark Rutte (Perdana Menteri)",
            countryCapital = "Amsterdam",
            countryIndependenceDay = "5 Mei",
            countryLanguage = "Belanda",
            countryCurrency = "Euro (EUR)",
            countryLandArea = "41.54341.543"
        ),
        Country(
            countryId = 16,
            countryName = "Luksemburg",
            countryInternationalName = "Grand Duchy of Luxembourg",
            countryFlagUrl = "https://upload.wikimedia.org/wikipedia/commons/thumb/d/da/Flag_of_Luxembourg.svg/640px-Flag_of_Luxembourg.svg.png",
            countryDescription = "Luksemburg atau resminya Keharyapatihan Luksemburg atau Kadipaten Agung Luksemburg adalah sebuah negara yang tidak berbatasan dengan laut di Eropa bagian barat laut, berbatasan dengan Prancis (perbatasan panjang 73 km), Jerman (panjang perbatasan 138 km) dan Belgia (panjang perbatasan 148 km). Merupakan negara dengan luas 2.586 kilometer. Sejak 1815, Luksemburg merupakan satu satunya negara di dunia yang masih dipimpin oleh adipati atau haryapatih sebagai kepala negara.",
            countryHeadGovernment = "Xavier Bettel (Perdana Menteri)",
            countryCapital = "Luxembourg",
            countryIndependenceDay = "22 Juni",
            countryLanguage = "Luxembourgish, Jerman, Prancis",
            countryCurrency = "Euro (EUR)",
            countryLandArea = "2.586"
        ),
        Country(
            countryId = 17,
            countryName = "Kanada",
            countryInternationalName = "Dominion of Canada",
            countryFlagUrl = "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d9/Flag_of_Canada_%28Pantone%29.svg/125px-Flag_of_Canada_%28Pantone%29.svg.png",
            countryDescription = "Kanada, dengan nama asli Dominion of Canada, merupakan negara paling utara di kawasan Amerika Utara. Kerajaan ni terdiri dalam 10 provinsi dan 3 teritori, dengan menganut sistem desentralisasi. Kanada berdiri pada tahun 1867, setelah disahkannya undang-undang Konfederasi. Ottawa menjadi ibukota negara ini. Kantor Gubernur Jenderal, Perdana Menteri, serta parlemen nasional terletak di kota tersebut. Kanada pernah menjadi jajahan Prancis; yang kemudian direbut oleh Inggris, hingga hari kemerdekaannya. Kini, negara ini menjadi anggota La Francophonie, sekaligus negara Persemakmuran Inggris. Luas Kanada mencapai 9.970.610 km². Negara ini tergolong negara maju, yang perekonomiannya bergantung pada hasil alam.\n" +
                    "\n Kanada merupakaan monarki konstitusional, dengan pemerintahan yang berbentuk demokrasi parlementer federal. Raja Charles III menjadi kepala negara.",
            countryHeadGovernment = "Justin Trudeau (Perdana Menteri)",
            countryCapital = "Ottawa",
            countryIndependenceDay = "1 Juli",
            countryLanguage = "Inggris, Prancis",
            countryCurrency = "Dolar Kanada (CAD)",
            countryLandArea = "9.970.610"
        ),
        Country(
            countryId = 18,
            countryName = "Italia",
            countryInternationalName = "Repubblica Italiana",
            countryFlagUrl = "https://upload.wikimedia.org/wikipedia/en/thumb/0/03/Flag_of_Italy.svg/255px-Flag_of_Italy.svg.png",
            countryDescription = "Italia adalah sebuah negara kesatuan republik parlementer di Eropa. Terletak di jantung Laut Mediterania. Italia berbatasan dengan Prancis, Swiss, Austria, Slovenia, San Marino dan Vatikan. Italia mencakup area seluas 301.338 km² (116.347 mi²), dan dipengaruhi oleh iklim sedang dan iklim mediterania. Dilihat dari bentuknya, peta Italia berbentuk seperti sepatu bot atau di Italia sering disebut lo Stivale. Dengan jumlah penduduk mencapai 61 juta jiwa, Italia merupakan negara anggota Uni Eropa ketiga yang paling banyak penduduknya setelah Jerman dan Prancis.",
            countryHeadGovernment = "Giorgia Meloni (Perdana Menteri)",
            countryCapital = "Italia",
            countryIndependenceDay = "2 Juni",
            countryLanguage = "Italia",
            countryCurrency = "Euro (EUR)",
            countryLandArea = "301.338"
        ),
        Country(
            countryId = 19,
            countryName = "Portugal",
            countryInternationalName = "República Portuguesa",
            countryFlagUrl = "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5c/Flag_of_Portugal.svg/125px-Flag_of_Portugal.svg.png",
            countryDescription = "Portugal atau Portugis dengan nama resmi disebut sebagai Republik Portugis adalah sebuah negara kesatuan yang bersistem semi-presidensial dengan berbentuk republik konstitusional di Eropa Selatan. Negara ini berbatasan dengan Spanyol di sebelah utara dan sebelah timur, sedangkan di sebelah barat berbatasan dengan Samudra Atlantik. Selain itu, Portugal juga mempunyai daerah di Madeira, Azores dan Kepulauan Selvagens. Portugal mengklaim sebuah daerah kecil bernama \"Olivença\" yang dikuasai Spanyol sejak Kongres Wina. Nama lama atau latin dari negara ini adalah Lusitania.",
            countryHeadGovernment = "António Costa (Perdana Menteri)",
            countryCapital = "Lisbon",
            countryIndependenceDay = "1 Desember",
            countryLanguage = "Portugis, Lusitanian, Miranda",
            countryCurrency = "Euro (EUR)",
            countryLandArea = "92.212"
        ),
        Country(
            countryId = 20,
            countryName = "Islandia",
            countryInternationalName = "Ísland",
            countryFlagUrl = "https://upload.wikimedia.org/wikipedia/commons/thumb/c/ce/Flag_of_Iceland.svg/125px-Flag_of_Iceland.svg.png",
            countryDescription = "Islandia yang secara resmi bernama Republik Islandia, adalah sebuah negara Nordik yang terletak di sebelah barat laut Eropa dan sebelah utara Samudera Atlantik, yang terdiri dari Pulau Islandia dan beberapa pulau kecil disekitarnya. Islandia terletak 300 kilometer di sebelah timur Greenland dan 1.000 kilometer dari Norwegia." +
                    "\nNegara ini memiliki populasi sebanyak 332.529 penduduk dan luas 103.000 km persegi, menjadikannya negara dengan penduduk terjarang di Eropa. Ibu kota dan kota terbesar di negara ini adalah Reykjavík. Reykjavík dan sekitarnya adalah tempat tinggal bagi dua pertiga populasi.",
            countryHeadGovernment = "Katrín Jakobsdóttir",
            countryCapital = "Reykjavík",
            countryIndependenceDay = "17 Juni",
            countryLanguage = "Islandia",
            countryCurrency = "Króna Islandia (ISK)",
            countryLandArea = "102.775"
        ),
        Country(
            countryId = 21,
            countryName = "Denmark",
            countryInternationalName = "Kongeriget Danmark",
            countryFlagUrl = "https://upload.wikimedia.org/wikipedia/commons/thumb/9/9c/Flag_of_Denmark.svg/125px-Flag_of_Denmark.svg.png",
            countryDescription = "Denmark adalah negara Nordik yang paling kecil dan paling utara. Denmark terletak di sebelah barat daya dari Swedia dan selatan dari Norwegia. Negara ini terletak di Skandinavia, Eropa Utara sehingga termasuk Uni Eropa namun tidak berada di Semenanjung Skandinavia.\n" +
                    "\nDenmark berbatasan dengan Laut Baltik dan Laut Utara. Wilayahnya meliputi sebuah semenanjung di Jerman utara bernama Jylland (Jutlandia), Kepulauan Fyn (Funen), Sjælland (Zealand), Vendsyssel-Thy, Lolland, Falster, Bornholm dan ratusan pulau kecil, yang sering disebut kepulauan Denmark. Denmark pernah lama menguasai Laut Baltik. Sebelum penggalian Terusan Kiel, jalan air menuju Laut Baltik hanya dapat dilewati melalui tiga Selat Denmark. Satu-satunya batas darat Denmark adalah dengan Jerman, sedangkan tetangganya yang dibatasi oleh laut adalah Swedia di timur laut dan Norwegia di utara.",
            countryHeadGovernment = "Mette Frederiksen (Perdana Menteri)",
            countryCapital = "Kopenhagen",
            countryIndependenceDay = "5 Juni",
            countryLanguage = "Denmark",
            countryCurrency = "Euro (EUR)",
            countryLandArea = "42.933"
        ),
        Country(
            countryId = 22,
            countryName = "Norwegia",
            countryInternationalName = "Kongeriket Norge",
            countryFlagUrl = "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d9/Flag_of_Norway.svg/125px-Flag_of_Norway.svg.png",
            countryDescription = "Norwegia atau Kerajaan Norwegia adalah sebuah negara Nordik di Semenanjung Skandinavia, di bagian ujung barat yang berbatasan dengan Swedia, Finlandia, Rusia, Britania Raya di barat daya, dan 1.000 kilometer dari Islandia di arah barat. Pantainya yang berada di Samudra Atlantik Utara dan Laut Barents adalah lokasi dari fyord terkenal. Svalbard dan Jan Mayen berada di bawah kedaulatan Norwegia berdasarkan Traktat Svalbard. Norwegia memiliki sebuah pulau bernama Bouvet yang terletak di Samudra Atlantik bagian selatan. Luas total dari negara Norwegia adalah 385,207 km².",
            countryHeadGovernment = "Jonas Gahr Støre (Perdana Menteri)",
            countryCapital = "Oslo",
            countryIndependenceDay = "17 Mei",
            countryLanguage = "Norwegia",
            countryCurrency = "Krona Norwegia (NOK)",
            countryLandArea = "385.207"
        ),
        Country(
            countryId = 23,
            countryName = "Yunani",
            countryInternationalName = "Ellinikí Dimokratía",
            countryFlagUrl = "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5c/Flag_of_Greece.svg/125px-Flag_of_Greece.svg.png",
            countryDescription = "secara resmi bernama Republik Yunani, dikenal pada zaman purba sebagai Hellas, adalah sebuah negara tempat lahirnya budaya Dunia Barat yang berada di Eropa bagian tenggara, terletak di ujung selatan Semenanjung Balkan, di bagian timur Laut Tengah (Mediterania).",
            countryHeadGovernment = "Kyriakos Mitsotakis (Perdana Menteri)",
            countryCapital = "Athena",
            countryIndependenceDay = "25 Maret",
            countryLanguage = "Yunani",
            countryCurrency = "Euro (EUR)",
            countryLandArea = "131.957 "
        ),
        Country(
            countryId = 24,
            countryName = "Turkiye",
            countryInternationalName = "Türkiye Cumhuriyeti",
            countryFlagUrl = "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b4/Flag_of_Turkey.svg/125px-Flag_of_Turkey.svg.png",
            countryDescription = "Turkiye secara resmi disebut sebagai Republik Turkiye adalah sebuah negara kesatuan dengan sistem presidensial di kawasan Eurasia. Wilayahnya terbentang dari Semenanjung Anatolia di Asia Barat Laut hingga daerah Balkan di Eropa Tenggara. Turkiye berbatasan dengan Laut Hitam di sebelah utara; Bulgaria di sebelah barat laut; Yunani dan Laut Aegea di sebelah barat; Georgia di timur laut; Armenia, Azerbaijan, dan Iran di sebelah timur; Irak dan Suriah di tenggara; dan Laut Mediterania di sebelah selatan. Laut Marmara yang merupakan bagian dari Turkiye digunakan untuk menandai batas wilayah benua Eropa dan benua Asia, sehingga Turkiye dikenal sebagai negara transkontinental.",
            countryHeadGovernment = "Recep Tayyip Erdoğan (Presiden)",
            countryCapital = "Ankara",
            countryIndependenceDay = "29 Oktober",
            countryLanguage = "Turkiye",
            countryCurrency = "Lira Turki (TRY)",
            countryLandArea = "783,562"
        ),
        Country(
            countryId = 25,
            countryName = "Jerman",
            countryInternationalName = "Deutschland",
            countryFlagUrl = "https://upload.wikimedia.org/wikipedia/commons/thumb/b/ba/Flag_of_Germany.svg/125px-Flag_of_Germany.svg.png",
            countryDescription = "Jerman secara resmi disebut sebagai Republik Federal Jerman adalah negara berbentuk federasi di Eropa. Negara ini memiliki posisi ekonomi dan politik yang sangat penting di Eropa maupun di dunia. Dengan luas 357.021 kilometer persegi dan jumlah penduduk sekitar 82 juta jiwa, negara dengan 16 negara bagian (Bundesland, jamak: Bundesländer) ini menjadi anggota kunci organisasi Uni Eropa (penduduk terbanyak), penghubung transportasi barang dan jasa antarnegara sekawasan, serta menjadi negara dengan penduduk imigran ketiga terbesar di dunia.",
            countryHeadGovernment = "Olaf Scholz (Kanselir)",
            countryCapital = "Berlin",
            countryIndependenceDay = "3 Oktober",
            countryLanguage = "Jerman",
            countryCurrency = "Euro (EUR)",
            countryLandArea = "357.386"
        ),
        Country(
            countryId = 26,
            countryName = "Spanyol",
            countryInternationalName = "España",
            countryFlagUrl = "https://upload.wikimedia.org/wikipedia/commons/thumb/8/89/Bandera_de_Espa%C3%B1a.svg/125px-Bandera_de_Espa%C3%B1a.svg.png",
            countryDescription = "Spanyol secara resmi dikenal dengan sebutan Kerajaan Spanyol adalah sebuah negara di Eropa barat daya yang bersama Portugal, terdapat di Semenanjung Iberia. Batas darat Spanyol dengan Eropa adalah Pegunungan Pirenia dengan Prancis dan Andorra. Wilayahnya terdiri dari kota Ceuta dan Melilla di Afrika Utara, Kepulauan Canary di Samudra Atlantik, dan berbagai pulau di Laut Tengah.\n" +
                    "\nWilayah Spanyol juga termasuk Kepulauan Balearic di Mediterania, Kepulauan Canary di Samudera Atlantik lepas pantai Afrika, dan dua kota otonom di Afrika Utara, Ceuta dan Melilla, yang berbatasan Maroko, ditambah Alboran, Kepulauan Chafarinas, Alhucemas, Vélez de la Gomera dan pulau kecil lainnya termasuk Perejil. Selain itu, kota Llívia adalah eksklave Spanyol terletak di dalam wilayah Prancis. Dengan luas 505.992 kilometer persegi (195.365 mil persegi), Spanyol adalah negara terbesar kedua di Eropa Barat dan Uni Eropa dan negara terbesar kelima di Eropa.",
            countryHeadGovernment = "Pedro Sánchez (Perdana Menteri)",
            countryCapital = "Madrid",
            countryIndependenceDay = "12 Oktober",
            countryLanguage = "Spanyol",
            countryCurrency = "Euro (EUR)",
            countryLandArea = "505.990"
        ),
        Country(
            countryId = 27,
            countryName = "Ceko",
            countryInternationalName = "Česká Republika",
            countryFlagUrl = "https://upload.wikimedia.org/wikipedia/commons/thumb/c/cb/Flag_of_the_Czech_Republic.svg/125px-Flag_of_the_Czech_Republic.svg.png",
            countryDescription = "Republik Ceko atau secara singkat Ceko atau Cekia adalah sebuah negara di Eropa Tengah yang terbentuk setelah bubarnya negara Cekoslowakia. Negara ini berbatasan dengan Jerman di sebelah barat dan utara, dengan Polandia di sebelah utara, dengan Slowakia di sebelah tenggara dan dengan Austria di sebelah selatan.\n" +
                    "\nDi negara ini terletak Sudetenland di mana dahulu tinggal suku bangsa Jerman, tetapi setelah Perang Dunia II, sebagian besar mereka dideportasi meskipun masih banyak orang Ceko yang menyandang nama Jerman. Kala itu sekitar 3,5 juta jiwa bangsa Jerman diusir.\n" +
                    "\nDi tanah Sudeten banyak terdapat industri, terutama industri kerajinan kristal dan bir.",
            countryHeadGovernment = "Petr Fiala (Perdana Menteri)",
            countryCapital = "Praha",
            countryIndependenceDay = "28 Oktober",
            countryLanguage = "Ceska",
            countryCurrency = "Koruna (CZK)",
            countryLandArea = "78.866"
        ),
        Country(
            countryId = 28,
            countryName = "Hungaria",
            countryInternationalName = "Hongaria",
            countryFlagUrl = "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c1/Flag_of_Hungary.svg/125px-Flag_of_Hungary.svg.png",
            countryDescription = "Hungaria adalah sebuah negara terkurung daratan di Eropa tengah. Negara ini terletak pada Cekungan Karpatia dan berbatasan dengan Austria di sebelah barat, Slowakia di sebelah utara, Ukraina di sebelah timur, Rumania di sebelah tenggara, Kroasia dan Serbia di sebelah selatan, Slovenia di sebelah barat daya. Dalam bahasa setempat, negara ini dikenal sebagai Magyarország yang berarti \"daerah Magyar\". Hungaria membentuk kumpulan Visegrád bersama Polandia, Slowakia dan Republik Ceko. Kota terbesar dan ibu kotanya adalah Budapest. Hungaria juga termasuk anggota NATO, Uni Eropa, Organisasi Kerja sama dan Perkembangan Ekonomi, dan Perjanjian Schengen. Bahasa resminya adalah bahasa Hungaria, yang merupakan bahasa non-Indo-Eropa yang paling banyak dituturkan di Eropa.",
            countryHeadGovernment = "Viktor Orbán (Perdana Menteri)",
            countryCapital = "Budapest",
            countryIndependenceDay = "15 Maret",
            countryLanguage = "Hungaria",
            countryCurrency = "Forint (HUF)",
            countryLandArea = "93.030"
        ),
        Country(
            countryId = 29,
            countryName = "Polandia",
            countryInternationalName = "Rzeczpospolita Polska",
            countryFlagUrl = "https://upload.wikimedia.org/wikipedia/commons/thumb/1/12/Flag_of_Poland.svg/125px-Flag_of_Poland.svg.png",
            countryDescription = "Polandia adalah sebuah negara republik di Eropa Tengah yang berbatasan langsung dengan Jerman di sebelah barat Perbatasan Oder-Neisse, Ceko, dan Slowakia di sebelah selatan, Rusia (Kaliningrad), Lituania di sebelah timur laut dan Belarus serta Ukraina di sebelah timur. Polandia adalah negara anggota Uni Eropa. Ibu kota Polandia dan kota terbesar adalah Warsawa.\n" +
                    "\nPolandia adalah negara yang maju dan kuat di kawasan ini. Negara ini memiliki ekonomi terbesar kedelapan dan salah satu yang paling dinamis di Uni Eropa dengan Indeks Pembangunan Manusia yang sangat tinggi.[6] Selain itu, Bursa Efek Polandia di Warsawa adalah salah satu yang terbesar dan paling penting di Eropa Tengah. Polandia mempertahankan ekonomi berpenghasilan tinggi bersama dengan standar hidup yang sangat tinggi, kualitas hidup, keselamatan, pendidikan, dan kebebasan ekonomi.",
            countryHeadGovernment = "Mateusz Morawiecki (Perdana Menteri)",
            countryCapital = "Warsaw",
            countryIndependenceDay = "11 November",
            countryLanguage = "Polandia",
            countryCurrency = "Złoty (PLN)",
            countryLandArea = "312.679"
        ),
        Country(
            countryId = 30,
            countryName = "Bulgaria",
            countryInternationalName = "Republika Bŭlgariya",
            countryFlagUrl = "https://upload.wikimedia.org/wikipedia/commons/thumb/9/9a/Flag_of_Bulgaria.svg/125px-Flag_of_Bulgaria.svg.png",
            countryDescription = "Bulgaria adalah sebuah negara di Eropa Tenggara. Bulgaria berbatasan dengan lima negara: Rumania di utara (sebagian besarnya di sepanjang Sungai Donau), Serbia, dan Republik Makedonia di barat, dan Yunani dan Turki di selatan. Laut Hitam membatasi negara ini di sebelah timur.\n" +
                    "\nDengan luas wilayah 110.994 km², Bulgaria menjadi negara terluas ke-16 di Eropa. Beberapa kawasan pegunungan membatasi bentang alamnya, yang paling terkenal adalah Pegunungan Balkan dan Pegunungan Rodopi, juga Pegunungan Rila, padanya terdapat puncak tertinggi di kawasan Balkan, yaitu Puncak Musala. Sebaliknya, Dataran Donau di utara dan Dataran Trakia Atas di selatan menjadi titik terendah sekaligus sebagai kawasan tersubur di Bulgaria. Pesisir Laut Hitam sepanjang 378 km meliputi seluruh batas timur negara ini. Pusat pemerintahan sekaligus kota terbesar Bulgaria adalah Sofia.",
            countryHeadGovernment = "Kiril Petkov (Perdana Menteri)",
            countryCapital = "Sofia",
            countryIndependenceDay = "3 Maret",
            countryLanguage = "Bulgaria",
            countryCurrency = "Lev Bulgaria (BGN)",
            countryLandArea = "110.994"
        ),
        Country(
            countryId = 31,
            countryName = "Estonia",
            countryInternationalName = "Eesti Vabariik",
            countryFlagUrl = "https://upload.wikimedia.org/wikipedia/commons/thumb/8/8f/Flag_of_Estonia.svg/125px-Flag_of_Estonia.svg.png",
            countryDescription = "Republik Estonia adalah sebuah negara berdaulat di kawasan Baltik di Eropa Utara. Estonia berbatasan dengan Teluk Finlandia di utara, dengan Laut Baltik di barat, dengan Latvia dan Teluk Riga di selatan (343 km), dan Danau Peipus (Peipsi) dan Rusia di timur (338,6 km). Di seberang barat Laut Baltik terletak Swedia, sedangkan di utaranya terdapat Finlandia. Sejak tanggal 21 Desember 2007, Estonia turut meratifikasi Perjanjian Schengen 1985, yakni perjanjian yang dibuat oleh sejumlah negara Eropa untuk menghapuskan pengawasan perbatasan di antara mereka. Wilayah Estonia seluas 45.227 km2 (17.462 sq mi), dan dipengaruhi oleh iklim sedang. Bangsa Estonia tergolong orang Fin Baltik, dan bahasa resminya adalah bahasa Esti yang serumpun dengan bahasa Suomi meskipun hanya mirip beberapa persen.",
            countryHeadGovernment = "Kaja Kallas (Perdana Menteri)",
            countryCapital = "Talinn",
            countryIndependenceDay = "24 Februari",
            countryLanguage = "Estonia",
            countryCurrency = "Euro (EUR)",
            countryLandArea = "45.227"
        ),
        Country(
            countryId = 32,
            countryName = "Latvia",
            countryInternationalName = "Latvijas Republika",
            countryFlagUrl = "https://upload.wikimedia.org/wikipedia/commons/thumb/8/84/Flag_of_Latvia.svg/125px-Flag_of_Latvia.svg.png",
            countryDescription = "Republik Latvia adalah sebuah negara di kawasan Baltik, Eropa Utara. Latvia berbatasan dengan Estonia (sepanjang 343 km) di utara, dengan Lithuania (sepanjang 588 km) di selatan, dengan Rusia (sepanjang 276 km) di timur, dengan Belarus (sepanjang 141 km) di tenggara, dan berbagi perbatasan bahari dengan Swedia di barat. Dengan penduduk sejumlah 2.070.371 jiwa dan wilayah seluas 64.589 km persegi, Latvia adalah salah satu negara yang berpenduduk sedikit dan jarang di Uni Eropa. Pusat pemerintahannya berada di Riga. Bahasa resminya adalah Bahasa Latvia dan satuan mata uangnya adalah Lats (Ls). Negara ini beriklim sedang. Negara ini bergabung dengan Uni Eropa pada 1 Mei 2004 dan dengan NATO pada 29 Maret 2004.",
            countryHeadGovernment = "Krišjānis Kariņš (Perdana Menteri)",
            countryCapital = "Riga",
            countryIndependenceDay = "18 November",
            countryLanguage = "Latvia",
            countryCurrency = "Euro (EUR)",
            countryLandArea = "64.589"
        ),
        Country(
            countryId = 33,
            countryName = "Lithuania",
            countryInternationalName = "Lietuvos Respublika",
            countryFlagUrl = "https://upload.wikimedia.org/wikipedia/commons/thumb/1/11/Flag_of_Lithuania.svg/125px-Flag_of_Lithuania.svg.png",
            countryDescription = "Republik Lituania adalah sebuah negara di Eropa Utara. Lituania merupakan salah satu dari tiga negara Baltik yang dekat dengan Laut Baltik. Negara ini berbatasan dengan Latvia di sebelah utara, Belarus di tenggara, Polandia di selatan, dan Oblast Kaliningrad milik Rusia di barat daya dan berbatasan dengan Laut Baltik dengan Swedia.\n" +
                    "\nSejak 2004, Lituania merupakan salah satu negara Uni Eropa yang memasuki kawasan Schengen, yang tidak memiliki kontrol perbatasan. Sejak 2015 negara milik kawasan euro. Lithuania adalah ekonomi maju dengan pendapatan tinggi, setelah mencapai standar hidup yang tinggi, tingkat kebebasan sipil Lituania, kebebasan media, kebebasan internet dan demokrasi sangat dihargai. Lituania adalah anggota Uni Eropa (sejak 2004), Dewan Eropa, NATO dan OECD.",
            countryHeadGovernment = "Ingrida Šimonytė (Perdana Menteri)",
            countryCapital = "Vilnius",
            countryIndependenceDay = "11 Maret",
            countryLanguage = "Lituavi",
            countryCurrency = "Euro (EUR)",
            countryLandArea = "65.300"
        ),
        Country(
            countryId = 34,
            countryName = "Rumania",
            countryInternationalName = "România",
            countryFlagUrl = "https://upload.wikimedia.org/wikipedia/commons/thumb/7/73/Flag_of_Romania.svg/125px-Flag_of_Romania.svg.png",
            countryDescription = "Rumania adalah negara yang terletak di Eropa Tengah dan Tenggara, di bagian utara Semenanjung Balkan dan berbatasan dengan Laut Hitam.[6] Hampir seluruh delta sungai Donau terletak di wilayah Rumania. Negara ini berbatasan dengan Hongaria dan Serbia di barat, Ukraina dan Republik Moldova di timur laut, dan Bulgaria di selatan.",
            countryHeadGovernment = "Nicolae Ciucă (Perdana Menteri)",
            countryCapital = "Bukares",
            countryIndependenceDay = "1 Desember",
            countryLanguage = "Rumania",
            countryCurrency = "Leu Rumania (RON)",
            countryLandArea = "238.391"
        ),
        Country(
            countryId = 35,
            countryName = "Slowakia",
            countryInternationalName = "Slovenská Republika",
            countryFlagUrl = "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e6/Flag_of_Slovakia.svg/125px-Flag_of_Slovakia.svg.png",
            countryDescription = "Republik Slowakia adalah negara berdaulat di Eropa Tengah pecahan Cekoslowakia. Negara yang terkurung di wilayah daratan ini berbatasan langsung dengan Polandia di utara, Republik Ceko di barat laut, Ukraina di timur, Hongaria di selatan, dan Austria di barat daya.\n" +
                    "\nSlowakia merupakan negara pegunungan dengan luas wilayah 49.000 km persegi dengan jumlah penduduk lebih dari 5.6 juta jiwa. Negara ini beribukota di Bratislava, dan kota terbesar keduanya adalah Kosice. Sebelumnya negara ini merupakan bagian dari kerajaan Moravia Besar dan Austro-Hongaria. Sejak tanggal 1 Januari 2009 Slowakia mulai menggunakan mata uang Euro.",
            countryHeadGovernment = "Eduard Heger (Perdana Menteri)",
            countryCapital = "Bratislava",
            countryIndependenceDay = "17 Juli",
            countryLanguage = "Slowakia",
            countryCurrency = "Euro (EUR)",
            countryLandArea = "49.035"
        ),
        Country(
            countryId = 36,
            countryName = "Slovenia",
            countryInternationalName = "Republika Slovenija",
            countryFlagUrl = "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f0/Flag_of_Slovenia.svg/125px-Flag_of_Slovenia.svg.png",
            countryDescription = "Republik Slovenia adalah sebuah negara pesisir sub-Alpen di Eropa Tengah. Slovenia berbatasan dengan Italia di barat, Austria di utara, Hongaria di timurlaut, Kroasia di tenggara, dan Laut Adriatik di baratdaya. Slovenia didominasi pegunungan dan hutan, dengan luas wilayah 20.271 kilometer persegi, dan dengan jumlah penduduk sebanyak 2.107.007 jiwa, yang 300.000 di antaranya menetap di kota terbesar dan pusat pemerintahan, Ljubljana. Etnis Slovenia membentuk mayoritas mutlak populasi negara. Bahasa Slovenia, salah satu anggota rumpun bahasa Slavia Selatan, merupakan bahasa resmi. Slovenia memiliki iklim yang didominasi iklim benua, dengan perkecualian kawasan pesisir dan Pegunungan Alpen Julian. Iklim sub-mediterania mencapai perpanjangan utara Pegunungan Alpen Dinari yang merentasi negara dalam arah barat laut-tenggara. Pegunungan Alpen Julian di barat laut memiliki iklim Alpen. Iklim benua semakin jelas menuju Cekungan Pannonia di Timur Laut. Kota terbesar dan pusat pemerintahan, Ljubljana, terletak di tengah-tengah negara.",
            countryHeadGovernment = "Janez Janša (Perdana Menteri)",
            countryCapital = "Ljubljana",
            countryIndependenceDay = "26 Desember",
            countryLanguage = "Slovenia",
            countryCurrency = "Euro (EUR)",
            countryLandArea = "20.273"
        ),
        Country(
            countryId = 37,
            countryName = "Albania",
            countryInternationalName = "Republika e Shqipërisë",
            countryFlagUrl = "https://upload.wikimedia.org/wikipedia/commons/thumb/3/36/Flag_of_Albania.svg/125px-Flag_of_Albania.svg.png",
            countryDescription = "Albania adalah sebuah negara yang terletak di Eropa Tenggara. Negara ini berbatasan dengan Montenegro di sebelah utara, Kosovo di timur laut, Makedonia Utara di timur, dan Yunani di selatan, Laut Adriatik terletak di sebelah barat Albania, sedangkan Laut Ionia di barat daya.\n" +
                    "\nAlbania di dalam bahasanya dipanggil Shqipëria, yang berarti Tanah Air Burung Elang. Orang Albania mengaitkan definisi ini sebagai julukan dari kaum mereka secara keseluruhan, dan julukan ini juga dikaitkan sebagai pengartian dari gambar burung elang berkepala dua di bendera dan emblem Albania (burung elang berkepala dua ini sebenarnya adalah lambang dari Kekaisaran Bizantium yang pernah menguasai daerah Balkan dan Anatolia, yang secara bergiliran diambil dari peradaban-peradaban pra-Romawi di Anatolia. Lambang ini juga dapat ditemukan di emblem negara-negara lain, seperti Rusia). Nama \"Albania\" pula mungkin berasal dari perkataan Indo-Eropa albh (putih).",
            countryHeadGovernment = "Edi Rama (Perdana Menteri)",
            countryCapital = "Tirana",
            countryIndependenceDay = "28 November",
            countryLanguage = "Albania",
            countryCurrency = "Lek (ALL)",
            countryLandArea = "28.748"
        ),
        Country(
            countryId = 38,
            countryName = "Kroasia",
            countryInternationalName = "Republika Hrvatska",
            countryFlagUrl = "https://upload.wikimedia.org/wikipedia/commons/thumb/1/1b/Flag_of_Croatia.svg/125px-Flag_of_Croatia.svg.png",
            countryDescription = "Republik Kroasia adalah negara Balkan di persimpangan Eropa Tengah dan Eropa Tenggara, dan juga merupakan negara yang berbentuk bulan sabit. Negara ini berbatasan dengan Slovenia di barat laut, Hongaria di timur laut, Serbia di timur, Bosnia dan Herzegovina dan Montenegro di tenggara, dan berbagi perbatasan laut dengan Italia di barat dan barat daya.\n" +
                    "\nDalam sejarahnya, negara ini merupakan negara republik untuk Republik Sosialis Federal Yugoslavia. Negara ini melepaskan diri dan memperoleh kemerdekaan pada 1991 dan merupakan anggota kandidat dari Uni Eropa, PBB, Organisasi untuk Keamanan dan Co-operasi di Eropa, Dewan Eropa, dan anggota tidak tetap dari Dewan Keamanan Perserikatan Bangsa-Bangsa untuk periode 2008-2009. Negara ini juga anggota Uni Eropa dan NATO. Kroasia resmi bergabung dengan NATO pada April 2009,[5] sehingga ada dua negara bekas anggota Republik Sosialis Federal Yugoslavia yang bergabung dengan aliansi militer tersebut, yaitu Kroasia dan Slovenia. Selain itu, Kroasia juga merupakan anggota dari Uni untuk Mediterania setelah didirikan pada 2008.",
            countryHeadGovernment = "Andrej Plenković (Perdana Menteri)",
            countryCapital = "Zagreb",
            countryIndependenceDay = "25 Juni",
            countryLanguage = "Kroasia",
            countryCurrency = "Euro (EUR)",
            countryLandArea = "56.594"
        ),
        Country(
            countryId = 39,
            countryName = "Montenegro",
            countryInternationalName = "Crna Gora",
            countryFlagUrl = "https://upload.wikimedia.org/wikipedia/commons/thumb/6/64/Flag_of_Montenegro.svg/125px-Flag_of_Montenegro.svg.png",
            countryDescription = "Montenegro adalah sebuah negara yang terletak di Eropa Selatan. Tepatnya berada di negara Balkan dan berbatasan dengan Laut Adriatik di selatan, Kroasia di barat, Bosnia dan Herzegovina dan Serbia di utara, dan Albania di selatan. Sebagai ibu kota negara adalah Podgorica. Menurut konstitusinya, negara ini merupakan negara demokratik, sosial, dan ekologikal.",
            countryHeadGovernment = "Dritan Abazović (Perdana Menteri)",
            countryCapital = "Podgorica",
            countryIndependenceDay = "21 Mei",
            countryLanguage = "Montenegro, Albania, Bosnia, Kroasia, Serbia",
            countryCurrency = "Euro (EUR)",
            countryLandArea = "13.812"
        ),
        Country(
            countryId = 40,
            countryName = "Makedonia Utara",
            countryInternationalName = "Republika Severna Makedonija",
            countryFlagUrl = "https://upload.wikimedia.org/wikipedia/commons/thumb/7/79/Flag_of_North_Macedonia.svg/125px-Flag_of_North_Macedonia.svg.png",
            countryDescription = "Republik Makedonia Utara adalah negara yang terletak di Semenanjung Balkan, Eropa Selatan. Negara ini berbatasan dengan Serbia dan Kosovo di utara, Albania di barat, Yunani di selatan, dan Bulgaria di timur.\n" +
                    "\nNegara ini disebut \"Republik Makedonia Bekas Yugoslavia\" (bahasa Inggris: Former Yugoslav Republic of Macedonia) oleh Perserikatan Bangsa-Bangsa sejak tahun 1993 sembari menunggu resolusi mengenai persengketaan penamaan dengan Yunani. Banyak institusi internasional dan negara lain telah mengakui negara ini dengan nama yang sama, meskipun mayoritas negara mengakui negara ini dengan nama konstitusional. Baru semejak tanggal 12 Februari 2019, Republik Makedonia resmi mengubah namanya menjadi Republik Makedonia Utara, mengakhiri sengketa nama.\n" +
                    "\nRepublik Makedonia Utara mencakup 35,8% wilayah dan 40,9% populasi wilayah Makedonia. Ibu kotanya adalah Skopje, yang dihuni 506.926 jiwa penduduk pada tahun 2004. Negara ini memiliki beberapa kota yang lebih kecil, seperti Bitola, Kumanovo, Prilep, Tetovo, Ohrid, Veles, Štip, Kočani, Gostivar, dan Strumica. Di Makedonia Utara, terdapat lebih daripada 50 danau alami dan waduk, dan juga memiliki enam belas gunung yang memiliki tinggi lebih dari 2.000 meter dari permukaan laut.\n" +
                    "\nNegara ini merupakan anggota PBB, NATO, dan Majelis Eropa; serta juga anggota dari La Francophonie, World Trade Organization (WTO), dan Organization for Security and Cooperation in Europe. Sejak Desember 2005, negara ini menjadi kandidat anggota Uni Eropa.",
            countryHeadGovernment = "Dimitar Kovačevski (Perdana Menteri)",
            countryCapital = "Skopje",
            countryIndependenceDay = "8 September",
            countryLanguage = "Makedonia, Albania",
            countryCurrency = "Denar Makedonia (MKD)",
            countryLandArea = "25.713"
        ),
    )
}